#spring.application.name=eureka-server
#server.port=9801
#spring.cloud.client.ipAddress=127.0.0.1
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.serviceUrl.defaultZone=http://127.0.0.1:9802/eureka/,http://127.0.0.1:9803/eureka/

server:
  port: 1100

spring:
  application:
    name: HelloServer
  cloud:
      client:
        ipAddress: 127.0.0.1

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
    ip-address: 127.0.0.1
  client:
    healthcheck:
      enabled: true                               # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://127.0.0.1:2100/eureka/  # 指定服务注册中心的地址